export const homePage = {
  url: 'http://localhost:4200/#/',
  component: 'app-home',
  aboutMeSection: '.about.section',
  latestProjectsSection: '.latest.section',
  featuredProject: '.latest.section .item.featured',
  projectItems: '.latest.section .item.row',
  findOutMoreLinks: '.latest.section .item.row .more-link',
  githubSection: '.github.section',
  contactInfoSection: '.info.section',
  skillsSection: '.skills.section',
  skillSet: '.skills.section .item',
  tooltipIcon: '.level-title span svg',
  languagesSection: '.languages.section',
  listedLanguages: '.languages.section .item',
  blogSection: '.blog.section',
  visitBlogButton: '.blog.section a.btn',
  dialog: '.modal-dialog',
  dialogClose: '.modal-header .close',
  tooltip: '.show.tooltip',
  moreLink: '.more-link'
};
